### ISSUE TITLE
Plugin is writing zero byte xlsx files

### ISSUE THREAD

**Issue by Hakaze** [segy/PhpExcel#1]
Hi Segy,

Hopefully you can help me figure this out sooner than later as I'm using your plugin for a project at work. I've followed your example completely and using my own model data. The script is iterating over all of my data correctly, however at 
$this->PhpExcel->output(); 
I end up with a zero byte xlsx file that errors out when opened in excel. My assumption is that it's either an issue with PHPExcel or an issue between your plugin and PHPExcel. 

Thanks

**Comment by sandeshgb** [comment]
@Hakaze What was the issue, because I'm still getting empty file as response
