### ISSUE TITLE
CakePHP 3.0

### ISSUE THREAD

**Issue by rrd108** [segy/PhpExcel#18]
Do you have plans for CakePHP 3?

**Comment by opunbuds** [comment]
+1

**Comment by segy** [comment]
Hello. I do not. I also switched to 3.0, but I found this package https://github.com/FriendsOfCake/CakePdf/tree/3.0 so I recommend you to use it too

**Comment by segy** [comment]
Hi guys. For sure I will need this in the near future and will put it here when I create something. Thanks for your support.

**Comment by rohanpande** [comment]
Thank you for the plugin. 
please make this compatible with cakephp 3.0
