### ISSUE TITLE
Add features in PhpExcelComponent

### ISSUE THREAD

**Issue by EOM** [segy/PhpExcel#20]
Hi, add for component
Line 201
Show Print: http://s25.postimg.org/iko3qp2en/Print_de_pantalla_713.jpg

CODE Copy:

        // Alignment VERTICAL
        if (isset($params['vertical'])){
            //PHPExcel_Style_Alignment::VERTICAL_JUSTIFY
            //PHPExcel_Style_Alignment::VERTICAL_LEFT
            //PHPExcel_Style_Alignment::VERTICAL_CENTER
            //PHPExcel_Style_Alignment::VERTICAL_RIGHT
            $this->_xls->getActiveSheet()->getStyle($this->_row)->getAlignment()->setVertical($params['vertical']);
        }else{
            $this->_xls->getActiveSheet()->getStyle($this->_row)->getAlignment()->setVertical(PHPExcel_Style_Alignment::VERTICAL_CENTER);
        }

        // Alignment HORIZONTAL
        if (isset($params['horizontal'])){
            //PHPExcel_Style_Alignment::HORIZONTAL_JUSTIFY
            //PHPExcel_Style_Alignment::HORIZONTAL_LEFT
            //PHPExcel_Style_Alignment::HORIZONTAL_CENTER
            //PHPExcel_Style_Alignment::HORIZONTAL_RIGHT
            $this->_xls->getActiveSheet()->getStyle($this->_row)->getAlignment()->setHorizontal($params['horizontal']);
        }else{
            $this->_xls->getActiveSheet()->getStyle($this->_row)->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
        }

**Comment by segy** [comment]
Hello. Feel free to create pull request. Thanks
