### ISSUE TITLE
How to handle large data and Out of memory issue?

### ISSUE THREAD

**Issue by anupalusoft** [segy/PhpExcel#24]
Hi,

I have huge amount of data like 20,000 records and i need export those all. Every time i do it takes time forever and ever saves. I did extended the `max_execution_time` but never helps. 

How would i do that to reduce its time and memory usage?
Can i do something that if user requested for export then it goes background and run. And when it completes then email to user. 

Please help.

**Comment by segy** [comment]
Hello

I have no idea how much memory this takes, but of course you can do the job in the background and then send email to user. But this is a little bit beyond the scope of this package :)

**Comment by anupalusoft** [comment]
@segy Thanks for your response. Just out of this plugin. How would i do that like running it in background and send email to user in CakePHP over linux server?
