### ISSUE TITLE
PHP 7 problem

### ISSUE THREAD

**Issue by seyfcom** [segy/PhpExcel#27]
Hello
I'm ont a huge expret in difference between php versions.
I use this helper in a cakephp app. I migrated to app to cakephp 2.10 to be able to use PHP7.
I get a error on exporting data to excel, the file is corrupted, not recognize, because I get an error in the process. But I don't find where...
Any idea?? anybody that has done this?

I know I should move to phpSpreadsheet but don't find an helper and no time to code it...
thanks!

**Comment by segy** [comment]
Hi @seyfcom 

I understand your problem, but sorry... I no longer support these packages. Feel free to open PR with fix. Thanks

**Comment by seyfcom** [comment]
I've found a way, disabling the autofilter.. that works for now... thanks anyway for the great helper! It worked for 4 years!!
